site_name: Monumenten
site_author: Tomer Gabay, Ben Verhees, Tiddo Loos
copyright: "2025, Woonstad Rotterdam"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - admonition
  - github-callouts

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
  - include-markdown:
  - mknotebooks

nav:
  - Home: index.md
  - Tutorial: tutorial.ipynb
